name: PackageReleasePluginCI
on:
  push:
    branches:
      - main

# Be sure to update these environment variables
# before pushing a new project with these build files.
env:
  PROJECT_NAME: pressable-cache-management
  VERSION_FILE_PATH: './pressable-cache-management.php'

permissions:
  contents: write

jobs:
  build:
    name: Package Release Project
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true
      - name: Build project zip # This would actually build your project, using zip for an example artifact
        run: git archive --format zip --output ${{ env.PROJECT_NAME }}.zip --prefix ${{ env.PROJECT_NAME }}/ main -0 # Build the zip, use the excludes file for zipping.
      - name: Install dependencies
        run: |-
          gem install octokit
      - name: Run the ruby build file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
          REPO_SHA: ${{ github.sha }}
          VERSION_FILE_PATH: ${{ env.VERSION_FILE_PATH }}
          ZIP_FILE_NAME: ${{ env.PROJECT_NAME }}.zip
          PROJECT_ZIP_NAME: ${{ env.PROJECT_NAME }}.zip
        run: ruby ./.github/workflows/build.rb
